# Generated by Django 4.0.2 on 2022-02-26 01:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameDv', models.CharField(max_length=255, unique=True, verbose_name='Tên Đơn Vị')),
            ],
            options={
                'verbose_name_plural': 'Đơn Vị Tính',
            },
        ),
        migrations.CreateModel(
            name='groupmaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameNVT', models.CharField(max_length=255, unique=True, verbose_name='Tên Nhóm Vật Tư')),
            ],
            options={
                'verbose_name_plural': 'Nhóm Vật Tư',
            },
        ),
        migrations.CreateModel(
            name='groupthietbi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameGroupTB', models.CharField(max_length=255, unique=True, verbose_name='Tên Nhóm Thiết Bị')),
            ],
            options={
                'verbose_name_plural': 'Nhóm Thiết Bị',
            },
        ),
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdVT', models.CharField(max_length=255, unique=True, verbose_name='Mã Vật Tư')),
                ('NameVT', models.CharField(max_length=255, unique=True, verbose_name='Tên Vật Tư')),
                ('IdDV', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DX.dv', verbose_name='Đơn Vị Tính')),
                ('IdNVTF', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DX.groupmaterial', verbose_name='Nhóm Vật Tư')),
            ],
            options={
                'verbose_name_plural': 'Vật Tư',
            },
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaNV', models.CharField(max_length=255, unique=True, verbose_name='Mã Nhân Viên')),
                ('TenNV', models.CharField(max_length=255, verbose_name='Tên Nhân Viên')),
                ('TuoiNV', models.IntegerField(verbose_name='Tuổi Nhân Viên')),
                ('Namlv', models.IntegerField(verbose_name='Số Năm Làm Việc')),
                ('BangLai', models.CharField(max_length=50, verbose_name='Bằng Lái')),
            ],
            options={
                'verbose_name_plural': 'Nhân Viên Bảo Dưỡng',
            },
        ),
        migrations.CreateModel(
            name='nhomxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tennhomxe', models.CharField(max_length=255, verbose_name='Tên Nhóm Xe')),
            ],
            options={
                'verbose_name_plural': 'Nhóm Xe Máy',
            },
        ),
        migrations.CreateModel(
            name='Xe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BienSoXe', models.CharField(max_length=255, unique=True, verbose_name='Biển Số Xe')),
                ('TenXe', models.CharField(max_length=255, verbose_name='Tên Xe')),
                ('IDNhomXe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DX.nhomxe')),
            ],
            options={
                'verbose_name_plural': 'Thông Tin Xe',
            },
        ),
        migrations.CreateModel(
            name='XeVao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sophieu', models.UUIDField(default=uuid.uuid4, verbose_name='Số Phiếu')),
                ('datetimeXevao', models.DateTimeField(verbose_name='Thời Gian Xe Vào')),
                ('Status', models.BooleanField(default=False)),
                ('datetimeXera', models.DateTimeField(blank=True, null=True, verbose_name='Thời Gian Xe Ra')),
                ('LyDoXeVao', models.TextField(max_length=500, verbose_name='Tình Trạng Xe Vào')),
                ('Lydo', models.TextField(max_length=500, verbose_name='Nội Dung Công Việc')),
                ('BienSoXe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DX.xe', verbose_name='Biển Số Xe')),
                ('NhanVienPT', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DX.nhanvien', verbose_name='Nhân Viên Phụ Trách')),
            ],
            options={
                'verbose_name_plural': 'Thông Tin Xe Vào',
            },
        ),
        migrations.CreateModel(
            name='VatTuDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dongia', models.FloatField(verbose_name='Đơn Giá')),
                ('SoLuong', models.PositiveIntegerField(verbose_name='Số Lượng')),
                ('thanhtien', models.FloatField(verbose_name='Thành Tiền')),
                ('TrangThaiKho', models.CharField(choices=[('Không', 'Không'), ('Có', 'Có')], max_length=50, verbose_name='Trạng Thái Kho')),
                ('TrangThaiXuat', models.CharField(choices=[('Chưa Xuất', 'Chưa Xuất'), ('Đã Xuất', 'Đã Xuất')], max_length=50, verbose_name='Trạng Thái Xuất')),
                ('DatetimeXuat', models.DateTimeField(blank=True, null=True, verbose_name='Thời Gian Xuất')),
                ('VtSudung', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DX.material', verbose_name='Vật Tư')),
                ('XeVao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DX.xevao')),
            ],
            options={
                'verbose_name_plural': 'Vật Tư Dùng Bảo Dưỡng Xe',
            },
        ),
        migrations.CreateModel(
            name='thietbi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameTB', models.CharField(max_length=255, unique=True, verbose_name='Tên Thiết Bị')),
                ('IdGroupTB', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DX.groupthietbi', verbose_name='Nhóm Thiết Bị')),
            ],
            options={
                'verbose_name_plural': 'Thiết Bị',
            },
        ),
    ]
