# Generated by Django 4.0.2 on 2022-03-02 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DX', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vattudung',
            name='TrangThaiXuat',
            field=models.CharField(choices=[('Đã Xuất', 'Đã Xuất'), ('Chưa Xuất', 'Chưa Xuất')], max_length=50, verbose_name='Trạng Thái Xuất'),
        ),
        migrations.AlterField(
            model_name='vattudung',
            name='dongia',
            field=models.TextField(verbose_name='Đơn Giá'),
        ),
        migrations.AlterField(
            model_name='vattudung',
            name='thanhtien',
            field=models.TextField(verbose_name='Thành Tiền'),
        ),
        migrations.AlterField(
            model_name='xe',
            name='IDNhomXe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DX.nhomxe', verbose_name='Tên Nhóm Xe'),
        ),
    ]
