# Generated by Django 4.0.2 on 2022-03-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DX', '0002_alter_vattudung_trangthaixuat_alter_vattudung_dongia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vattudung',
            name='TrangThaiKho',
            field=models.CharField(choices=[('Có', 'Có'), ('Không', 'Không')], max_length=50, verbose_name='Trạng Thái Kho'),
        ),
        migrations.AlterField(
            model_name='vattudung',
            name='dongia',
            field=models.FloatField(verbose_name='Đơn Giá'),
        ),
        migrations.AlterField(
            model_name='vattudung',
            name='thanhtien',
            field=models.FloatField(verbose_name='Thành Tiền'),
        ),
    ]
